version: '3.1'

services:

  prefixphp:
    image: wordpress:latest
    ports:
      - HOST_PORT:80
    environment:
      WORDPRESS_DB_HOST: prefixmysql
      WORDPRESS_DB_USER: wp_prefix
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp_prefix
    volumes:
      - prefixphp:/var/www/html
    restart: unless-stopped
    networks:
      bridge:
        aliases:
          - prefixphp

  prefixmysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp_prefix
      MYSQL_USER: wp_prefix
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - prefixmysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      bridge:
        aliases:
          - prefixmysql

networks:
  bridge:
#    name: nginxbridge
#    external: true

volumes:
  prefixphp:
  prefixmysql:
