version: '3.1'

services:

  prefix_php:
    image: wordpress:latest
    ports:
      - HOST_PORT:80
    environment:
      WORDPRESS_DB_HOST: prefix_mysql
      WORDPRESS_DB_USER: wp_prefix
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp_prefix
    volumes:
      - prefix_php:/var/www/html
    restart: unless-stopped
    networks:
      bridge:
        aliases:
          - prefix_php

  prefix_mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp_prefix
      MYSQL_USER: wp_prefix
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - prefix_mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      bridge:
        aliases:
          - prefix_mysql

networks:
  bridge:
#    name: nginxbridge
#    external: true

volumes:
  prefix_php:
  prefix_mysql:
